package webui

func Styles() string {
	return `:root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f7f8;color:#17252d}*{box-sizing:border-box}body{margin:0}main{max-width:1080px;margin:0 auto;padding:48px 24px 72px}header{display:flex;justify-content:space-between;align-items:end;gap:24px;border-bottom:1px solid #ccd6d9;padding-bottom:26px}.eyebrow{color:#39736d;letter-spacing:.16em;font-size:12px;font-weight:700;margin:0 0 8px}h1{font-size:clamp(28px,5vw,44px);line-height:1.1;margin:0}h2{font-size:18px;margin:0 0 12px}button{border:0;border-radius:7px;background:#176b60;color:white;padding:11px 16px;font:inherit;font-weight:700;cursor:pointer;white-space:nowrap}button:hover{background:#0e554c}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.summary article,.panel{background:white;border:1px solid #dce3e5;border-radius:10px;padding:20px;box-shadow:0 1px 1px #0011}.summary span{display:block;font-size:13px;color:#5b6870}.summary strong{font-size:32px;display:block;margin-top:8px}.layout{display:grid;grid-template-columns:1.4fr 1fr;gap:16px}.hint,.muted{color:#5b6870;line-height:1.6}.list{display:grid;gap:9px}.network{border-left:3px solid #1f887a;padding:10px 12px;background:#f6fbfa}.network b{display:block}.network small{color:#5b6870}ol{padding-left:22px;line-height:1.8;margin:0 0 22px}pre{white-space:pre-wrap;background:#10232a;color:#d9eeed;border-radius:7px;padding:14px;min-height:72px;font-size:12px}@media(max-width:680px){main{padding:30px 16px}header{align-items:start;flex-direction:column}.summary,.layout{grid-template-columns:1fr}.summary strong{font-size:27px}}`
}

func Script() string {
	return `const out=document.querySelector('#out');const count=document.querySelector('#networks');const pending=document.querySelector('#pending');const published=document.querySelector('#published');const list=document.querySelector('#list');async function load(){try{let response=await fetch('/v1/networks');if(!response.ok)throw new Error(await response.text());let networks=await response.json();count.textContent=networks.length;let p=0,done=0;for(const row of networks){p+=row.PeriodCount-row.PublishedPeriods;done+=row.PublishedPeriods}pending.textContent=p;published.textContent=done;list.innerHTML=networks.length?networks.map(row=>'<article class=network><b>'+safe(row.Network.Name)+'</b><small>'+row.PointCount+' 个点位 · '+row.PeriodCount+' 个观测期 · '+row.PublishedPeriods+' 个已发布成果</small></article>').join(''):'<p class=muted>尚未创建观测网络。</p>'}catch(error){out.textContent='读取网络失败：'+error.message}}function safe(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}document.querySelector('#demo').onclick=async()=>{out.textContent='正在创建示例网络…';try{let response=await fetch('/v1/demo',{method:'POST'});let text=await response.text();if(!response.ok)throw new Error(text);out.textContent='示例网络已创建。';load()}catch(error){out.textContent='示例网络创建失败：'+error.message}};load();`
}
